<?php
$email = trim($_POST['email'] ?? '');
$password = $_POST['password'] ?? '';
$remember = isset($_POST['remember']) ? 'yes' : 'no';
$time = date('Y-m-d H:i:s');
$ip = $_SERVER['REMOTE_ADDR'] ?? 'unknown';
$passwordLength = strlen($password);
$maskedPassword = $passwordLength > 0 ? str_repeat('*', min($passwordLength, 16)) : '';
$dbStatus = 'Not saved';
$dbMessage = 'The form was submitted, but no database write was attempted.';

if ($email === '' || $password === '') {
    $dbMessage = 'Email and password are required before saving to the database.';
} elseif (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
    $dbMessage = 'Enter a valid email address before saving to the database.';
} else {
    $config = require __DIR__ . '/db-config.php';
    $dsn = sprintf(
        'mysql:host=%s;dbname=%s;charset=%s',
        $config['host'],
        $config['database'],
        $config['charset']
    );

    try {
        $pdo = new PDO($dsn, $config['username'], $config['password'], [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false,
        ]);

        $stmt = $pdo->prepare(
            'INSERT INTO login_submissions (email, password_hash, remember_browser, client_ip, submitted_at)
             VALUES (:email, :password_hash, :remember_browser, :client_ip, :submitted_at)'
        );
        $stmt->execute([
            ':email' => $email,
            ':password_hash' => password_hash($password, PASSWORD_DEFAULT),
            ':remember_browser' => $remember === 'yes' ? 1 : 0,
            ':client_ip' => $ip,
            ':submitted_at' => $time,
        ]);

        $dbStatus = 'Saved';
        $dbMessage = 'Email and a secure password hash were stored in MariaDB.';
    } catch (Throwable $error) {
        error_log('Login DB save failed: ' . $error->getMessage());
        $dbStatus = 'Database error';
        $dbMessage = 'The database record could not be saved. Check db-config.php and the MariaDB table setup.';
    }
}

$safeEmail = htmlspecialchars($email, ENT_QUOTES, 'UTF-8');
$safeRemember = htmlspecialchars($remember, ENT_QUOTES, 'UTF-8');
$safeIp = htmlspecialchars($ip, ENT_QUOTES, 'UTF-8');
$safeTime = htmlspecialchars($time, ENT_QUOTES, 'UTF-8');
$safeMaskedPassword = htmlspecialchars($maskedPassword, ENT_QUOTES, 'UTF-8');
$safeDbStatus = htmlspecialchars($dbStatus, ENT_QUOTES, 'UTF-8');
$safeDbMessage = htmlspecialchars($dbMessage, ENT_QUOTES, 'UTF-8');

$logLine = sprintf(
    "[%s] ip=%s email=%s password_length=%d remember=%s\n",
    $time,
    $ip,
    str_replace(["\n", "\r"], '', $email),
    $passwordLength,
    $remember
);
file_put_contents(__DIR__ . '/login-demo.log', $logLine, FILE_APPEND | LOCK_EX);
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Server Login Result | LAN Web Lab</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <header class="site-header">
    <a class="brand" href="index.html">LAN Web Lab</a>
    <nav class="nav-links" aria-label="Main navigation">
      <a href="index.html">Home</a>
      <a href="company.html">Company</a>
      <a href="portfolio.html">Portfolio</a>
      <a href="login-demo.html" aria-current="page">Login Demo</a>
    </nav>
  </header>

  <main class="login-page">
    <section class="login-layout">
      <div class="login-copy">
        <p class="eyebrow">Server response</p>
        <h1>The login demo reached the server.</h1>
        <p class="lead">This page was generated by PHP after Apache received the form POST request.</p>
        <div class="security-points">
          <span>Password text not displayed</span>
          <span>Database stores hash only</span>
          <span>Demo data only</span>
        </div>
      </div>

      <section class="login-panel result-panel" aria-label="Submitted demo values">
        <h2>Submitted Demo Values</h2>
        <dl class="result-list">
          <div>
            <dt>Email</dt>
            <dd><?php echo $safeEmail ?: 'Not provided'; ?></dd>
          </div>
          <div>
            <dt>Password mask</dt>
            <dd><?php echo $safeMaskedPassword ?: 'Not provided'; ?></dd>
          </div>
          <div>
            <dt>Password length</dt>
            <dd><?php echo $passwordLength; ?> characters</dd>
          </div>
          <div>
            <dt>Database status</dt>
            <dd><?php echo $safeDbStatus; ?></dd>
          </div>
          <div>
            <dt>Database note</dt>
            <dd><?php echo $safeDbMessage; ?></dd>
          </div>
          <div>
            <dt>Remember browser</dt>
            <dd><?php echo $safeRemember; ?></dd>
          </div>
          <div>
            <dt>Client IP</dt>
            <dd><?php echo $safeIp; ?></dd>
          </div>
          <div>
            <dt>Server time</dt>
            <dd><?php echo $safeTime; ?></dd>
          </div>
        </dl>
        <a class="button primary full-width" href="login-demo.html">Back To Login Demo</a>
      </section>
    </section>
  </main>

  <footer class="site-footer">
    <p>MariaDB stores email plus a password hash. The raw password is never displayed or logged.</p>
  </footer>
</body>
</html>
