<?php
$email = trim($_POST['email'] ?? '');
$password = $_POST['password'] ?? '';
$remember = isset($_POST['remember']) ? 'yes' : 'no';
$time = date('Y-m-d H:i:s');
$ip = $_SERVER['REMOTE_ADDR'] ?? 'unknown';
$passwordLength = strlen($password);
$maskedPassword = $passwordLength > 0 ? str_repeat('*', min($passwordLength, 16)) : '';

$safeEmail = htmlspecialchars($email, ENT_QUOTES, 'UTF-8');
$safeRemember = htmlspecialchars($remember, ENT_QUOTES, 'UTF-8');
$safeIp = htmlspecialchars($ip, ENT_QUOTES, 'UTF-8');
$safeTime = htmlspecialchars($time, ENT_QUOTES, 'UTF-8');
$safeMaskedPassword = htmlspecialchars($maskedPassword, ENT_QUOTES, 'UTF-8');

$logLine = sprintf(
    "[%s] ip=%s email=%s password_length=%d remember=%s\n",
    $time,
    $ip,
    str_replace(["\n", "\r"], '', $email),
    $passwordLength,
    $remember
);
file_put_contents(__DIR__ . '/login-demo.log', $logLine, FILE_APPEND | LOCK_EX);
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Server Login Result | LAN Web Lab</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <header class="site-header">
    <a class="brand" href="index.html">LAN Web Lab</a>
    <nav class="nav-links" aria-label="Main navigation">
      <a href="index.html">Home</a>
      <a href="company.html">Company</a>
      <a href="portfolio.html">Portfolio</a>
      <a href="login-demo.html" aria-current="page">Login Demo</a>
    </nav>
  </header>

  <main class="login-page">
    <section class="login-layout">
      <div class="login-copy">
        <p class="eyebrow">Server response</p>
        <h1>The login demo reached the server.</h1>
        <p class="lead">This page was generated by PHP after Apache received the form POST request.</p>
        <div class="security-points">
          <span>Password text not displayed</span>
          <span>Log stores length only</span>
          <span>Demo data only</span>
        </div>
      </div>

      <section class="login-panel result-panel" aria-label="Submitted demo values">
        <h2>Submitted Demo Values</h2>
        <dl class="result-list">
          <div>
            <dt>Email</dt>
            <dd><?php echo $safeEmail ?: 'Not provided'; ?></dd>
          </div>
          <div>
            <dt>Password mask</dt>
            <dd><?php echo $safeMaskedPassword ?: 'Not provided'; ?></dd>
          </div>
          <div>
            <dt>Password length</dt>
            <dd><?php echo $passwordLength; ?> characters</dd>
          </div>
          <div>
            <dt>Remember browser</dt>
            <dd><?php echo $safeRemember; ?></dd>
          </div>
          <div>
            <dt>Client IP</dt>
            <dd><?php echo $safeIp; ?></dd>
          </div>
          <div>
            <dt>Server time</dt>
            <dd><?php echo $safeTime; ?></dd>
          </div>
        </dl>
        <a class="button primary full-width" href="login-demo.html">Back To Login Demo</a>
      </section>
    </section>
  </main>

  <footer class="site-footer">
    <p>Server log file: login-demo.log. It records username and password length only.</p>
  </footer>
</body>
</html>
